### ISSUE TITLE
The project specifies python 3.6 as a lower python version bound, but uses python 3.8 features

### ISSUE THREAD

**Issue by manniche** [MrGreenTea/topological-sort-backport#1]
e.g. https://github.com/MrGreenTea/topological-sort-backport/blob/master/graphlib/sorter.py#L57 will throw a `SyntaxError: invalid syntax` when executed with a python < 3.8 as the `:=` operator was introduced in [3.8](https://www.python.org/dev/peps/pep-0572/)

**Comment by MrGreenTea** [comment]
Hi @manniche thanks for the report.
That seems easy enough to fix :)

**Comment by MrGreenTea** [comment]
HI @manniche I've finally got around to fixing this. I've released it now on pypi.org as version 0.4.0 

https://github.com/MrGreenTea/topological-sort-backport/releases/tag/v0.4.0
